<?php
/**
 * Plugin Name: Pool Quote Compare
 * Description: Lets customers upload 2+ pool quotes (PDF/DOCX) and receive an AI-generated comparison powered by Claude Opus 4.7 (1M context). Saves every submission, can email the response to the customer, and shows the agent prompt for transparency.
 * Version: 1.0.0
 * Requires PHP: 7.4
 * Requires at least: 6.0
 * Author: Pool Quote Compare
 * License: GPL-2.0-or-later
 * Text Domain: pool-quote-compare
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'PQC_VERSION', '1.0.0' );
define( 'PQC_PLUGIN_FILE', __FILE__ );
define( 'PQC_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'PQC_PLUGIN_URL', plugin_dir_url( __FILE__ ) );
define( 'PQC_OPTION_KEY', 'pqc_settings' );
define( 'PQC_TABLE', 'pqc_submissions' );

require_once PQC_PLUGIN_DIR . 'includes/class-pqc-storage.php';
require_once PQC_PLUGIN_DIR . 'includes/class-pqc-parser.php';
require_once PQC_PLUGIN_DIR . 'includes/class-pqc-markdown.php';
require_once PQC_PLUGIN_DIR . 'includes/class-pqc-companies-house.php';
require_once PQC_PLUGIN_DIR . 'includes/class-pqc-claude.php';
require_once PQC_PLUGIN_DIR . 'includes/class-pqc-admin.php';
require_once PQC_PLUGIN_DIR . 'includes/class-pqc-frontend.php';
require_once PQC_PLUGIN_DIR . 'includes/class-pqc-ajax.php';

register_activation_hook( __FILE__, [ 'PQC_Storage', 'activate' ] );

add_action( 'plugins_loaded', function () {
	PQC_Admin::init();
	PQC_Frontend::init();
	PQC_Ajax::init();
} );

function pqc_default_system_prompt() {
	$path = PQC_PLUGIN_DIR . 'includes/agent-prompt.md';
	if ( file_exists( $path ) ) {
		return file_get_contents( $path );
	}
	return '';
}

function pqc_get_settings() {
	$defaults = [
		'api_key'                 => '',
		'companies_house_api_key' => '',
		'system_prompt'           => pqc_default_system_prompt(),
		'model'                   => 'claude-opus-4-7',
		'max_tokens'              => 16000,
		'enable_web_search'       => 1,
		'pdf_extraction_mode'     => 'text_first',
		'max_file_mb'         => 25,
		'max_files'           => 5,
		'email_from_name'     => get_bloginfo( 'name' ),
		'email_from_address'  => get_option( 'admin_email' ),
		'email_subject'       => __( 'Your pool quote comparison', 'pool-quote-compare' ),
		'email_intro'         => __( 'Thanks for using our pool quote comparison tool. Your AI-generated comparison is below.', 'pool-quote-compare' ),
		'disclaimer'          => __( "Important: this comparison is generated by an AI agent and is intended as decision support, not a decision. The analysis depends entirely on the quotes you supplied and any information found via web search — it can get things wrong, miss details, or make reasonable but imperfect assumptions. Please read each quote and contract in full, visit reference installations, and verify key facts (warranty terms, equipment specs, company registration, insurances) directly with each contractor before paying any deposit. We accept no liability for decisions made on the basis of this analysis.", 'pool-quote-compare' ),
		'thank_you_url'       => '',
		'thank_you_heading'   => __( 'Thanks — your quotes are on their way to the agent.', 'pool-quote-compare' ),
		'thank_you_message'   => __( "Our AI agent is now reading your quotes, cross-checking Companies House, and searching reviews. This usually takes up to 10 minutes. The full comparison will be emailed to the address you gave us. If it isn't in your inbox within 15 minutes, please check your spam folder.", 'pool-quote-compare' ),
		'bcc_admin'           => 1,
	];
	$saved = get_option( PQC_OPTION_KEY, [] );
	if ( ! is_array( $saved ) ) {
		$saved = [];
	}
	return array_merge( $defaults, $saved );
}
